import styled from "styled-components";
import Head from "next/head";
import Board from "../components/Board";
import { Luckiest_Guy } from "next/font/google";
import Fire from "@/components/Icons/Fire";
import BackLink from "@/components/BackLink";

const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const Header = styled.header`
  width: 45rem;
  padding: 0.5rem;
  margin: 0;
  color: #fff;
  display: flex;
  justify-content: space-between;
  align-items: center;

  & h1 {
    padding-top: 15px;
  }
`;

export default function BoardPage() {
  return (
    <>
      <Head>
        <title>Monopoly (on Fire)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Fire />
        <h1 className={luckiestGuy.className}>Monopoly (on Fire)</h1>
        <Fire />
        <BackLink color="#fff" />
      </Header>
      <main>
        <Board />
      </main>
    </>
  );
}
