import Head from "next/head";
import type { Player } from "../types/Player";
import Link from "next/link";

interface HomeProps {
  players: Player[];
  addPlayer: () => void;
}

export default function Home({ players, addPlayer }: HomeProps) {
  return (
    <>
      <Head>
        <title>Monopoly (on Fire)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Monopoly (on Fire)</h1>
      <h2>Select amount of players:</h2>
      <p>{players.length}</p>
      <button type="button" onClick={addPlayer}>
        Add player
      </button>
      <Link href="/board">Start</Link>
    </>
  );
}
