import { useState } from "react";
import styled from "styled-components";
import Head from "next/head";
import type { Avatar } from "@/types/Avatar";
import type { Color } from "@/types/Color";
import NewGameForm from "@/components/NewGameForm";
import Player from "@/components/Player";

interface HomeProps {
  players: Avatar[];
  avatars: Avatar[];
  colors: Color[];
  updateOpponents: (arg0: string) => void;
  user: { name: string; username: string; color: string };
  updateUser: (arg0: string, arg1: string) => void;
}

const Main = styled.main`
  display: grid;
  padding: 1rem;
  border-radius: 0.5rem;
  background-color: #fff;
  grid-template-areas: "headline headline headline" "title title title" "user-input form form";
`;

const Headline = styled.h1`
  grid-area: headline;
`;

const Title = styled.h2`
  grid-area: title;
`;

const CurrentStateOfUserInput = styled.div`
  width: 250px;
  grid-area: user-input;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 1rem;

  & p {
    margin: 0;
  }
`;

export default function Home({
  avatars,
  colors,
  updateOpponents,
  user,
  updateUser,
}: HomeProps) {
  const [currentStep, setCurrentStep] = useState(1);

  function updateCurrentStep(step: number) {
    setCurrentStep(step);
  }

  return (
    <>
      <Head>
        <title>Monopoly (on Fire)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Headline>Monopoly (on Fire)</Headline>
        <Title id="game-start">Start a new game:</Title>
        <CurrentStateOfUserInput>
          <Player
            selectedAvatar={user.name}
            selectedColor={user.color}
            userName={user.username}
            colors={colors}
          />
        </CurrentStateOfUserInput>
        <NewGameForm
          updateOpponents={updateOpponents}
          avatars={avatars}
          colors={colors}
          currentStep={currentStep}
          updateCurrentStep={updateCurrentStep}
          user={user}
          updateUser={updateUser}
        />
      </Main>
    </>
  );
}
