import Head from "next/head";
import Board from "../components/Board";
import { fields } from "../db";

export default function Home() {
  return (
    <>
      <Head>
        <title>Monopoly (on Fire)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Monopoly (on Fire)</h1>
      <Board fields={fields} />
    </>
  );
}
