"use client";

import "@/styles.css";
import "@/themes.styles.css";
import styles from "./layout.module.css";
import { usePathname } from "next/navigation";
import BackLink from "@/components/BackLink";
import { ReactNode } from "react";
import { PlayersProvider } from "@/context";

export default function RootLayout({ children }: { children: ReactNode }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <head>
        <title>Pyropoly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <PlayersProvider>
          <main className={styles.main}>
            <header className={styles.header}>
              <h1 className={styles.headline}>Pyropoly</h1>
              {pathname !== "/" && <BackLink color={"dark"} />}
            </header>
            {children}
          </main>
        </PlayersProvider>
      </body>
    </html>
  );
}
