"use client";

import "@/styles.css";
import "@/themes.styles.css";
import { ReactNode } from "react";
import { PlayersProvider } from "@/context";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Pyropoly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <PlayersProvider>{children}</PlayersProvider>
      </body>
    </html>
  );
}
