import Head from "next/head";
import styled from "styled-components";
import BackLink from "./BackLink";
import { useRouter } from "next/router";
import { Headline } from "./Headline";

const Header = styled.header`
  position: relative;
`;

const Main = styled.main`
  width: 45rem;
  padding: 2rem 1rem 1rem;
  border-radius: 0.5rem;
  background-color: #fff;
  height: 85%;
`;

export default function Layout({ children }: { children: React.ReactNode }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Pyropoly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Header>
          <Headline>Pyropoly</Headline>
          {router.pathname !== "/" && (
            <BackLink color={"var(--sapphire-blue)"} />
          )}
        </Header>
        {children}
      </Main>
    </>
  );
}
