import Head from "next/head";
import styled from "styled-components";
import BackLink from "./BackLink";
import { useRouter } from "next/router";

const Header = styled.header`
  position: relative;
`;

const Main = styled.main`
  width: 45rem;
  padding: 2rem 1rem 1rem;
  border-radius: 0.5rem;
  background-color: #fff;
  height: 90%;
`;

const Headline = styled.h1`
  font-size: 3rem;
  padding: 0.8rem 0 0;
  text-align: center;
  font-family: var(--luckiest-font);
`;

export default function Layout({ children }: { children: React.ReactNode }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Monopoly (on Fire)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Header>
          <Headline>Monopoly (on Fire)</Headline>
          {router.pathname !== "/" && <BackLink color={"var(--bg-color)"} />}
        </Header>
        {children}
      </Main>
    </>
  );
}
